#### general settings
name: MWGAN
use_tb_logger: true
model: mwgan
distortion: sr
scale: 1
gpu_ids: [1]
memory_len: 2

#### datasets
datasets:
  train:
    name: YUV_all
    mode: SEV
    dataroot: '/media/iceclear/yuhang/YUV_lmdb_rgb224_42/'
    datarootGT: '/media/iceclear/yuhang/YUV_lmdb_rgb224_42/'
    dataroot_GT: '/media/iceclear/iceking/YUV_lmdb_rgb224_all_42/GT.lmdb'
    dataroot_LQ: '/media/iceclear/iceking/YUV_lmdb_rgb224_all_42/LQ.lmdb'

    N_frames: 5
    interval_list: [1]
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 8
    GT_size: 224
    LQ_size: 224
    use_flip: True
    use_rot: True
    color: RGB
  val:
    name: YUV_all
    mode: SEV
    cache_data: True
    N_frames: 5
    padding: new_info
    dataroot: '/media/iceclear/yuhang/YUV_lmdb_test_rgb_42/'
    datarootGT: '/media/iceclear/yuhang/YUV_lmdb_test_rgb_42/'
    dataroot_GT: '/media/iceclear/yuhang/YUV_lmdb_test_rgb_42/BasketballDrill832x480_GT.lmdb'
    dataroot_LQ: '/media/iceclear/yuhang/YUV_lmdb_test_rgb_42/BasketballDrill832x480_LQ.lmdb'

#### network structures
network_G:
  which_model_G: DenseMWNet
  use_snorm: True
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 5
network_D:
  which_model_D: discriminator_Multi_light
  use_snorm: True
  n_scale: 3
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/psnr_new_rgb_180000.pth
  pretrain_model_others: ../resnet_18_8s_cityscapes_best.pth
  strict_load: True
  # resume_state: ../experiments/MWGAN/training_state/255000.state
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  only_G: False
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 300000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 150000, 300000, 450000]
  lr_gamma: 0.5

  lpips_criterion: lpips
  lpips_weight: 0
  feature_criterion: l1
  feature_weight: !!float 1e-1
  pixel_criterion: l1
  pixel_weight: 1

  gan_type: lsgan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 2
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3
  redata_freq: !!float 1
  save_test_img: True
  save_test_img_num: 5 #-1 all
  # val_freq: 1

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  # save_checkpoint_freq: 1
