#### general settings
name: MWGAN
use_tb_logger: true
model: mwgan
distortion: sr
scale: 1
gpu_ids: [0]
memory_len: 2

#### datasets
datasets:
  train:
    name: YUV_all
    mode: SEV
    dataroot: '/media/iceclear/iceking/YUV_lmdb_yuv224_37/'
    datarootGT: '/media/iceclear/iceking/YUV_lmdb_yuv224_37/'
    dataroot_GT: ''
    dataroot_LQ: ''

    N_frames: 5
    interval_list: [1]
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 8
    GT_size: 224
    LQ_size: 224
    use_flip: True
    use_rot: True
    color: Y
  val:
    name: YUV_all
    mode: SEV
    cache_data: True
    N_frames: 5
    padding: new_info
    dataroot: '/media/iceclear/iceking/HM_lmdb_test_Yonly_37/'
    datarootGT: '/media/iceclear/iceking/HM_lmdb_test_Yonly_32/'
    dataroot_GT: ''
    dataroot_LQ: ''

#### network structures
network_G:
  which_model_G: DenseMWNet
  use_snorm: True
  in_nc: 1
  out_nc: 1
  nf: 64
  nb: 5
network_D:
  which_model_D: discriminator_Multi_light
  use_snorm: True
  n_scale: 1
  in_nc: 1
  nf: 64

#### path
path:
  pretrain_model_G: ../experiments/MW-GAN-PSNR37/models/125000_G_255000_130000.pth
  pretrain_model_others: ../resnet_18_8s_cityscapes_best.pth
  strict_load: True
  # resume_state: ../experiments/SEVGAN/training_state/125000.state
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  only_G: True
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 250000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 150000, 300000, 450000]
  lr_gamma: 0.5

  lpips_criterion: lpips
  lpips_weight: 0
  feature_criterion: l1
  feature_weight: 0
  pixel_criterion: l2
  pixel_weight: 1

  gan_type: lsgan  # gan | ragan
  gan_weight: 0

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3
  redata_freq: !!float 1
  save_test_img: True
  save_test_img_num: 5 #-1 all
  # val_freq: 1

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  # save_checkpoint_freq: 1
