# general settings
name: MWGAN_ECCV_PSNR
model_type: MWGANModel_ECCV_PSNR
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: YUV_37
    type: YUVDataset
    dataroot_gt: ../../dataset/YUV_GT_img_crop_new/
    dataroot_lq: ../../dataset/YUV_img_crop_37_new/
    test_mode: False
    io_backend:
      type: disk

    num_frame: 3
    gt_size: 224
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: YUV_37
    type: YUVTestDataset
    dataroot_gt: /media/minglang/iceking1/YUV_GT_img_crop_test_new/
    dataroot_lq: /media/minglang/iceking1/YUV_img_crop_37_test_new/

    cache_data: false
    io_backend:
      type: disk

    num_frame: 3
    frame_limited: 20
    padding: reflection

# network structures
network_g:
  type: DenseMWNet_ECCV
  in_nc: 3
  out_nc: 3
  nf: 64
  gc: 32
  nb: 6
  # use_snorm: True

# path
path:
  pretrain_network_g: ~
  strict_load_g: True
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  motion_opt:
    type: L1Loss
    loss_weight: 10
    reduction: mean

# validation settings
val:
  # val_freq: 1
  val_freq: !!float 5e3
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    dpsnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    # lpips: # metric name, can be arbitrary
    #   type: calculate_lpips
    #   crop_border: 0
    #   test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: False
